### ISSUE TITLE
@metamask/jazzicon

### ISSUE THREAD

**Issue by sakshamjaiswal1** [ssbarbee/react-metamask-avatar#3]
✘ [ERROR] Could not resolve "@metamask/jazzicon"

    node_modules/react-metamask-avatar/dist/esm/index.js:1:34:
      1 │ import e from"react";import a from"@metamask/jazzicon";import r from"@emotion/styled";const s={},t=e=>{const{address:r,size:t}=e;if(!r||42!==r.length)return"";const i=`${t}...
        ╵                                   ~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@metamask/jazzicon" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "@emotion/styled"

    node_modules/react-metamask-avatar/dist/esm/index.js:1:68:
      1 │ import e from"react";import a from"@metamask/jazzicon";import r from"@emotion/styled";const s={},t=e=>{const{address:r,size:t}=e;if(!r||42!==r.length)return"";const i=`${t}...
        ╵                                                                     ~~~~~~~~~~~~~~~~~

  You can mark the path "@emotion/styled" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

/home/saksham/Work/sperax/chaquen_frontend/node_modules/esbuild/lib/main.js:1651
  let error = new Error(text);
              ^

Error: Build failed with 2 errors:
node_modules/react-metamask-avatar/dist/esm/index.js:1:34: ERROR: Could not resolve "@metamask/jazzicon"
node_modules/react-metamask-avatar/dist/esm/index.js:1:68: ERROR: Could not resolve "@emotion/styled"
    at failureErrorWithLog (/home/saksham/Work/sperax/chaquen_frontend/node_modules/esbuild/lib/main.js:1651:15)
    at /home/saksham/Work/sperax/chaquen_frontend/node_modules/esbuild/lib/main.js:1059:25
    at /home/saksham/Work/sperax/chaquen_frontend/node_modules/esbuild/lib/main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js v20.9.0

**Desktop (please complete the following information):**
 - Device: acer nitro
 - OS: ubuntu
 - Browser -brave

![image](https://github.com/ssbarbee/react-metamask-avatar/assets/75566599/290beb37-dd0f-4106-bbe3-8f4a6de18fe1)

**Comment by ssbarbee** [comment]
Hey @sakshamjaiswal1 thanks for the comments.

I do think that the libraries you mentioned are peer dependencies. This means that you as integrator need to provide them. 

This keeps the bundle size low of this package and allows you as integrator to specify what version of emotion/styled you want to use. 

🙏🙏🙏

Let me know if this doesnt work for you.
